=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module ApprovalAPIClient
  class Decision
    
    UNDECIDED = "undecided".freeze
    APPROVED = "approved".freeze
    DENIED = "denied".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Decision.constants.select{|c| Decision::const_get(c) == value}
      raise "Invalid ENUM value #{value} for class #Decision" if constantValues.empty?
      value
    end
  end

end
