=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module ApprovalAPIClient
  class Operation
    
    APPROVE = "approve".freeze
    DENY = "deny".freeze
    NOTIFY = "notify".freeze
    MEMO = "memo".freeze
    SKIP = "skip".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Operation.constants.select{|c| Operation::const_get(c) == value}
      raise "Invalid ENUM value #{value} for class #Operation" if constantValues.empty?
      value
    end
  end

end
