=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module ApprovalAPIClient
  class State
    
    PENDING = "pending".freeze
    SKIPPED = "skipped".freeze
    NOTIFIED = "notified".freeze
    FINISHED = "finished".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = State.constants.select{|c| State::const_get(c) == value}
      raise "Invalid ENUM value #{value} for class #State" if constantValues.empty?
      value
    end
  end

end
