=begin
#Insights Service Approval APIs

#APIs to query approval service

The version of the OpenAPI document: 1.2.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for ApprovalApiClient::ActionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActionApi' do
  before do
    # run before each test
    @api_instance = ApprovalApiClient::ActionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionApi' do
    it 'should create an instance of ActionApi' do
      expect(@api_instance).to be_instance_of(ApprovalApiClient::ActionApi)
    end
  end

  # unit tests for create_action
  # Add an action to a given request
  # Add an action to a given request. Admin can do approve, deny, memo, and cancel operations; approver can do approve, deny and memo operations; while requester can do only cancel operation.
  # @param request_id Id of request
  # @param action Action object that will be added
  # @param [Hash] opts the optional parameters
  # @return [Action]
  describe 'create_action test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_actions_by_request
  # List all actions of a request
  # Return actions in a given request, available for admin/approver
  # @param request_id Id of request
  # @param [Hash] opts the optional parameters
  # @return [ActionCollection]
  describe 'list_actions_by_request test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_action
  # Return an user action by id
  # Return an user action by id, available to all
  # @param id Query by id
  # @param [Hash] opts the optional parameters
  # @return [Action]
  describe 'show_action test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
