=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for ApprovalApiClient::GraphqlApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GraphqlApi' do
  before do
    # run before each test
    @instance = ApprovalApiClient::GraphqlApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GraphqlApi' do
    it 'should create an instance of GraphqlApi' do
      expect(@instance).to be_instance_of(ApprovalApiClient::GraphqlApi)
    end
  end

  # unit tests for post_graphql
  # Perform a GraphQL Query
  # Performs a GraphQL Query
  # @param graphql_in GraphQL Query Request
  # @param [Hash] opts the optional parameters
  # @return [GraphqlOut]
  describe 'post_graphql test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
