=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ApprovalAPIClient::RequestersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RequestersApi' do
  before do
    # run before each test
    @instance = ApprovalAPIClient::RequestersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestersApi' do
    it 'should create an instance of RequestersApi' do
      expect(@instance).to be_instance_of(ApprovalAPIClient::RequestersApi)
    end
  end

  # unit tests for add_request
  # Add an approval request by given parameters
  # Add an approval request by given parameters
  # @param workflow_id Id of workflow
  # @param body Parameters need to create a request
  # @param [Hash] opts the optional parameters
  # @return [Request]
  describe 'add_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_request_by_id
  # Return an approval request by given id
  # Return an approval request by given id
  # @param id Query by id
  # @param [Hash] opts the optional parameters
  # @return [Request]
  describe 'fetch_request_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_request_stages
  # Return an array of stages by given request id
  # Return an array of stages by given request id
  # @param request_id Id of request
  # @param [Hash] opts the optional parameters
  # @return [Array<Stage>]
  describe 'fetch_request_stages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_stage_by_id
  # Return an approval stage by given id
  # Return an approval stage by given id
  # @param id Query by id
  # @param [Hash] opts the optional parameters
  # @return [Stage]
  describe 'fetch_stage_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
