=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for ApprovalAPIClient::TemplateApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplateApi' do
  before do
    # run before each test
    @instance = ApprovalAPIClient::TemplateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplateApi' do
    it 'should create an instance of TemplateApi' do
      expect(@instance).to be_instance_of(ApprovalAPIClient::TemplateApi)
    end
  end

  # unit tests for list_templates
  # Return all templates
  # Return all templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit How many items to return at one time (max 1000)
  # @option opts [Integer] :offset Starting Offset
  # @return [TemplateOutCollection]
  describe 'list_templates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_template
  # Return a template by given id
  # Return a template by given id
  # @param id Query by id
  # @param [Hash] opts the optional parameters
  # @return [TemplateOut]
  describe 'show_template test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
