=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ApprovalAPIClient::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = ApprovalAPIClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(ApprovalAPIClient::UsersApi)
    end
  end

  # unit tests for add_request
  # Add a new approval request
  # request creation may not be via rest
  # @param workflow_id id of workflow
  # @param body Approval request object that needs to be added
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_request_by_id
  # Retrieves approval request by given id
  # 
  # @param id query by id
  # @param [Hash] opts the optional parameters
  # @return [Request]
  describe 'fetch_request_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_request_stages
  # Returns stages by given request id
  # Returns stages by request id
  # @param request_id id of request
  # @param [Hash] opts the optional parameters
  # @return [Array<Stage>]
  describe 'fetch_request_stages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
