=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ApprovalAPIClient::ActionOut
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ActionOut' do
  before do
    # run before each test
    @instance = ApprovalAPIClient::ActionOut.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionOut' do
    it 'should create an instance of ActionOut' do
      expect(@instance).to be_instance_of(ApprovalAPIClient::ActionOut)
    end
  end
  describe 'test attribute "processed_by"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "operation"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["approve", "deny", "notify", "memo", "skip"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.operation = value }.not_to raise_error
       #end
    end
  end

end

