=begin
#Insights Service Approval APIs

#APIs to query approval service

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ApprovalApiClient::GraphqlIn
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GraphqlIn' do
  before do
    # run before each test
    @instance = ApprovalApiClient::GraphqlIn.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GraphqlIn' do
    it 'should create an instance of GraphqlIn' do
      expect(@instance).to be_instance_of(ApprovalApiClient::GraphqlIn)
    end
  end
  describe 'test attribute "query"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "operation_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "variables"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
