=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ApprovalAPIClient::StageOut
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StageOut' do
  before do
    # run before each test
    @instance = ApprovalAPIClient::StageOut.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StageOut' do
    it 'should create an instance of StageOut' do
      expect(@instance).to be_instance_of(ApprovalAPIClient::StageOut)
    end
  end
  describe 'test attribute "group_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["pending", "skipped", "notified", "finished"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.state = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "decision"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["undecided", "approved", "denied"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.decision = value }.not_to raise_error
       #end
    end
  end

end

