=begin
#Insights Service Approval APIs

#APIs to query approval service

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

# Common files
require 'approval-api-client-ruby/api_client'
require 'approval-api-client-ruby/api_error'
require 'approval-api-client-ruby/version'
require 'approval-api-client-ruby/configuration'

# Models
require 'approval-api-client-ruby/models/action_in'
require 'approval-api-client-ruby/models/action_out'
require 'approval-api-client-ruby/models/action_out_collection'
require 'approval-api-client-ruby/models/collection_links'
require 'approval-api-client-ruby/models/collection_metadata'
require 'approval-api-client-ruby/models/request_in'
require 'approval-api-client-ruby/models/request_out'
require 'approval-api-client-ruby/models/request_out_collection'
require 'approval-api-client-ruby/models/stage_out'
require 'approval-api-client-ruby/models/stage_out_collection'
require 'approval-api-client-ruby/models/template_out'
require 'approval-api-client-ruby/models/template_out_collection'
require 'approval-api-client-ruby/models/workflow_in'
require 'approval-api-client-ruby/models/workflow_out'
require 'approval-api-client-ruby/models/workflow_out_collection'

# APIs
require 'approval-api-client-ruby/api/action_api'
require 'approval-api-client-ruby/api/request_api'
require 'approval-api-client-ruby/api/stage_api'
require 'approval-api-client-ruby/api/template_api'
require 'approval-api-client-ruby/api/workflow_api'

module ApprovalApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   ApprovalApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
